sudo: required
dist: trusty
language: c
cache:
    directories:
        # Cache test dependencies that would normally be re-compiled for every build.
        # This directory is unique for each entry of the build matrix per:
        # https://docs.travis-ci.com/user/caching/#Caches-and-build-matrices
        - test-deps

osx_image: xcode8

os:
  - linux

matrix:
  include:
    - os : linux
      env: TESTS=sidewinder
      addons:
        apt:
          packages:
            - clang-3.9
            - llvm-3.9
            - llvm-3.9-dev
#    - os : linux
#      env: TESTS=ctverif


  allow_failures:
    - os: osx
    - env: S2N_LIBCRYPTO=openssl-1.1.x-master BUILD_S2N=true TESTS=integration GCC6_REQUIRED=true
    # Optional until we resolve broken remote dependency: https://github.com/awslabs/s2n/pull/615
    - env: TESTS=ctverif

  fast_finish: true

before_install:
  - source .travis/s2n_setup_env.sh

install:
  - .travis/s2n_install_test_dependencies.sh
  
script:
  - travis_wait .travis/s2n_travis_build.sh
