sudo: required
dist: trusty
language: c
cache:
    directories:
        # Cache test dependencies that would normally be re-compiled for every build.
        # This directory is unique for each entry of the build matrix per:
        # https://docs.travis-ci.com/user/caching/#Caches-and-build-matrices
        - test-deps

osx_image: xcode8

os:
  - linux

matrix:
  include:
  - os : linux
    env : TESTS=sawHMAC SAW_HMAC_TEST=md5    SAW=true GCC6_REQUIRED=false
    addons: &sawaddons
      apt:
        packages:
          - clang-3.8
          - llvm-3.8
  fast_finish: true

before_install:
  - source .travis/s2n_setup_env.sh

install:
  - .travis/s2n_install_test_dependencies.sh
  
script:
  - .travis/s2n_travis_build.sh
